version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/
      - ./build/docker/server.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/
    working_dir: /var/www
